### ISSUE TITLE
disappointed

### ISSUE THREAD

**Issue by jxwufan** [shameonzju/shameonzju.github.io#10]

**Comment by jxwufan** [comment]
btw, 虽然不太懂前端，但是否能将每个事件作为独立的markdown文件来组织？这样也有利于管理

**Comment by zijinoier** [comment]
> btw, 虽然不太懂前端，但是否能将每个事件作为独立的markdown文件来组织？这样也有利于管理

This website is currently working on a static HTML5 file, which does not support this feature.

However, some framework like Hexo or Jekyll may support markdown file to html.

If anyone convert this project to such framework, I am willing to accept the pull request. 😃

**Comment by shameonzju** [comment]
> btw, 虽然不太懂前端，但是否能将每个事件作为独立的markdown文件来组织？这样也有利于管理

This website is currently working on a static HTML5 file, which does not support this feature.

However, some framework like Hexo or Jekyll may support markdown file to html.

If anyone convert this project to such framework, I am willing to accept the pull request. smiley

**Comment by jxwufan** [comment]
If no one does this conversion by the end of this week, I may try to find someone to help.

**Comment by jxwufan** [comment]
per what you did to #13, please continue to play your game anonymously, I don't believe you can do whatever you want behind the scene forever.
